name: microlang
description: A minimalist programming language compiler that compiles to JavaScript. Features multiple types, expressions, control structures, and functions.
version: 2.0.0
repository: https://github.com/Qharny/MicroLang

environment:
  sdk: ^3.5.1

executables:
  microlang: microlang

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
